[project]
name = "simple-token"
description = "A simple token contract for the BlockDev workshop"
authors = ["Your Name your.email@example.com"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.simple-token]
path = "contracts/simple-token.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2